version: '3.6'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    user: postgres
  web:
    build:
      context: .
    command: ./run-app.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=docker.settings
      - PGPASSWORD=postgres